find -mmin -1000 -type f > a
while read file; do [[ $(wc -l < "$file") = 3 ]] && tail -n +3 "$file" | grep 2012-10-31 && echo "$file"; done < a

./drivers-md-dm-integrity.c:sparse:bad-constant-expression
./Section-mismatch-in-reference-from-the-function-integrity_init_keyring()-to-the-variable-.init.data:pubkey
./drivers-md-dm-integrity.c:warning:dm_int_verify_io-uses-dynamic-stack-allocation
./security-integrity-ima-ima_dir.c:warning:ima_dir_collect-uses-dynamic-stack-allocation
./security-integrity-ima-ima_main.c:ERROR:iint-is-NULL-but-dereferenced.
./drivers-md-dm-integrity.c:inconsistent-IS_ERR-and-PTR_ERR-PTR_ERR-on-line
./security-integrity-module.c:sparse:symbol-mod_verify_sig-was-not-declared.-Should-it-be-static
./security-integrity-digsig_pubkey.c:sparse:incorrect-type-in-argument-(different-base-types)
./security-integrity-ima-ima_dir.c:sparse:bad-constant-expression
./drivers-md-dm-integrity.c:sparse:cannot-size-expression
./drivers-staging-comedi-drivers-addi-data-addi_common.c-i_ADDI_Attach()-error:we-previously-assumed-this_board-pc_EepromChip-could-be-null-(see-line-)
./drivers-md-dm-integrity.c:warning:comparison-of-distinct-pointer-types-lacks-a-cast
./drivers-staging-et131x-et131x.c:sparse:incorrect-type-in-assignment-(different-address-spaces)
./drivers-staging-et131x-et131x.c:sparse:incorrect-type-in-argument-(different-address-spaces)
./drivers-tty-serial-serial_core.c:warning:left-shift-count-width-of-type
./drivers-gpu-drm-i915-intel_ddi.c:sparse:mixing-different-enum-types
./include-video-vga.h:warning:cast-to-pointer-from-integer-of-different-size
./drivers-tty-serial-8250_pci.c:warning:cast-to-pointer-from-integer-of-different-size
./arch-xtensa-kernel-entry.S:Warning:value-truncated-to
./arch-xtensa-kernel-irq.c:warning:passing-argument-of-xtensa_irq_unmask-makes-pointer-from-integer-without-a-cast
./arch-xtensa-kernel-irq.c:warning:passing-argument-of-xtensa_irq_mask-makes-pointer-from-integer-without-a-cast
./drivers-pci-quirks.c:warning:initialization-makes-pointer-from-integer-without-a-cast
./drivers-pci-quirks.c:warning:assignment-makes-pointer-from-integer-without-a-cast
./kernel-fork.c:sparse:symbol-sys_fork-was-not-declared.-Should-it-be-static
./kernel-fork.c:sparse:symbol-sys_vfork-was-not-declared.-Should-it-be-static
./kernel-fork.c:sparse:symbol-sys_clone-was-not-declared.-Should-it-be-static
./arch-blackfin-kernel-process.c:error:regs-undeclared-(first-use-in-this-function)
./arch-cris-arch-v10-kernel-process.c:error:invalid-type-argument-of-unary-(have-int-)
./arch-m32r-kernel-process.c:error:p-undeclared-(first-use-in-this-function)
./arch-parisc-kernel-entry.S:Error:Invalid-operands
./arch-xtensa-include-uapi-asm-unistd.h:error:sys_clone-undeclared-here-(not-in-a-function)
./include-linux-spinlock.h:warning:ulp-may-be-used-uninitialized-in-this-function
./arch-blackfin-include-asm-gpio.h:error:redefinition-of-gpio_get_value
./arch-blackfin-include-asm-gpio.h:error:redefinition-of-gpio_set_value
./arch-blackfin-include-asm-gpio.h:error:redefinition-of-gpio_cansleep
./arch-blackfin-include-asm-gpio.h:error:redefinition-of-gpio_to_irq
./include-asm-generic-gpio.h:error:redefinition-of-gpio_get_value
./include-asm-generic-gpio.h:error:redefinition-of-gpio_set_value
./include-asm-generic-gpio.h:error:redefinition-of-gpio_to_irq
./arch-sh-include-asm-gpio.h:error:redefinition-of-gpio_get_value
./arch-sh-include-asm-gpio.h:error:redefinition-of-gpio_set_value
./arch-sh-include-asm-gpio.h:error:redefinition-of-gpio_cansleep
./arch-sh-include-asm-gpio.h:error:redefinition-of-gpio_to_irq
./arch-avr32-mach-at32ap-include-mach-gpio.h:error:redefinition-of-gpio_get_value
./include-asm-generic-gpio.h:error:previous-definition-of-gpio_get_value-was-here
./arch-avr32-mach-at32ap-include-mach-gpio.h:error:redefinition-of-gpio_set_value
./include-asm-generic-gpio.h:error:previous-definition-of-gpio_set_value-was-here
./arch-avr32-mach-at32ap-include-mach-gpio.h:error:redefinition-of-gpio_cansleep
./include-asm-generic-gpio.h:error:previous-definition-of-gpio_cansleep-was-here
./arch-avr32-mach-at32ap-include-mach-gpio.h:error:redefinition-of-gpio_to_irq
./include-asm-generic-gpio.h:error:previous-definition-of-gpio_to_irq-was-here
./mm-slab_common.c:warning:format-td-expects-argument-of-type-ptrdiff_t-but-argument-has-type-size_t
